FROM gcc


## INSTALLING SSH SERVER 
RUN apt-get update && apt-get install -y openssh-server

## INSTALLING GDB AND GCC 
RUN apt-get -y install gcc && \
	apt-get -y install gdb

RUN apt-get install gdb
RUN mkdir /var/run/sshd
RUN echo 'root:this' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
